### ISSUE TITLE
numstart.dat no longer considers increment of restart saves

### ISSUE THREAD

**Issue by eleighschwarz** [SimVascular/svSolver#92] opened 2020-12-09 20:19 UTC
numstart.dat in the procs-case folder used to track the last saved restart file saved so that it could be restarted from the last saved checkpoint. For example, if the simulation was start:0 stop:1000 timesteps_between_restars:100, then if the simulation ran to timestep 540 and got interrupted, numstart.dat would hold 500 so that the simulation could restart from restart.500.XX- the last saved restart file.

Now, however, it updates numstart.dat at every time step so that numstart.dat would have 540 in it if it was interrupted at step 540. If you try to restart the simulation, it will throw an error as there is no restart.540.XX to restart from. To restart a simulation now requires manually changing the numstart file, which doesn't work for automatically restarting a simulation.

A solution would be to change numstart.dat back to how it used to operate, or have it automatically restart from the highest restart file number (i.e. restart.YY.XX, highest YY) so that simulations can automatically be restarted after interruption without manual intervention.

**Comment by ktbolt** [comment] 2020-12-09 22:06
@eleighschwarz svSolver has recently been changed to recover history data from job termination. I don't think we've seen this problem since the changes though.

@mrp089 Do you think this could be caused by the changes you made to recover from job termination?

**Comment by eleighschwarz** [comment] 2020-12-09 22:42
I recompiled from github today and was still having problems (with the restart.YY.XX does not exist), is there a different method of restarting simulations?

**Comment by mrp089** [comment] 2020-12-10 00:51
I'm looking into it. @eleighschwarz which version did you use when it was still working? It doesn't seem like this bug was introduced recently.

**Comment by mrp089** [comment] 2020-12-10 04:20
Okay, turns it I did in fact introduce that bug. When splitting writing output files and incrementing numstart.dat into two functions in 6bef433, I forgot to check if numstart.dat should be incremented in this time step. Fixed in #93

**Closed** 2020-12-11 18:25 UTC
Labels: bug
